version: '3'
services:
  rust:
    build:
        context: .
        dockerfile: ./docker/rust/Dockerfile
    environment:
        USER: root
        command: cargo watch -x "run" -w src
    volumes:
        - .:/app:cached
    stdin_open: true
    tty: true

  nextjs:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: nextjs
    volumes:
      - ./app:/usr/src/app
    command: "yarn dev"
    ports:
      - "3000:3000"

  storybook:
    build: ./docker/
    command: "yarn storybook"
    ports:
      - "6006:6006"
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=development