version: '3'
services:
  rust:
    build:
        context: .
        dockerfile: ./docker/rust/Dockerfile
    environment:
        USER: root
        command: cargo watch -x "run" -w src
    volumes:
        - .:/app:cached
    stdin_open: true
    tty: true

  nextjs:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd app && npm run dev"
    ports:
      - "3000:3000"
    tty: true